<?php

declare(strict_types=1);

namespace Wtyd\GitHooks\Jobs\CommitMessage;

/**
 * Pure validator for a commit-message subject (FEAT-16). Receives an already
 * resolved rule set (preset overrides applied — see {@see CommitMessagePresets})
 * and returns a {@see ValidationOutcome}. No disk, no git, no shell — fully
 * unit-testable and deterministic, so it runs identically on Linux, macOS and
 * Windows (REQ-033).
 *
 * Evaluation order is fixed (REQ-015) so the user sees a reproducible result;
 * the first failing rule aborts and is reported:
 *   merge-skip → forbid-empty → min-length → max-length → pattern
 *   → forbid-trailing-period → subject-case
 *
 * Length is measured in UTF-8 code points (mb_strlen), not bytes (CON-005).
 */
class CommitMessageValidator
{
    /** Detects an optional Conventional-Commits prefix `tipo(scope)?: `. */
    private const CC_PREFIX = '/^[a-z]+(\([\w-]+\))?:\s+/';

    /**
     * Extract the subject from a raw commit message: strip a leading UTF-8 BOM,
     * normalize CRLF/CR to LF, and take the first line (up to the first `\n`).
     */
    public static function extractSubject(string $rawMessage): string
    {
        $message = $rawMessage;
        if (strncmp($message, "\xEF\xBB\xBF", 3) === 0) {
            $message = substr($message, 3);
        }
        $message = str_replace(["\r\n", "\r"], "\n", $message);
        $newlinePos = strpos($message, "\n");
        return $newlinePos === false ? $message : substr($message, 0, $newlinePos);
    }

    /**
     * @param array<string, mixed> $rules
     *
     * @SuppressWarnings(PHPMD.CyclomaticComplexity) One branch per rule in the fixed
     *   evaluation order; each is an independent, documented outcome.
     * @SuppressWarnings(PHPMD.NPathComplexity) Same reason.
     */
    public function validate(string $subject, array $rules): ValidationOutcome
    {
        $length = (int) mb_strlen($subject);

        $mergeAllowed = (bool) ($rules['merge-allowed'] ?? true);
        if ($mergeAllowed && $this->isMergeLike($subject)) {
            return ValidationOutcome::mergeSkip($length);
        }

        $forbidEmpty = (bool) ($rules['forbid-empty'] ?? true);
        if ($forbidEmpty && trim($subject) === '') {
            return ValidationOutcome::fail(
                'forbid-empty',
                'Commit message subject must not be empty.',
                null,
                $length
            );
        }

        if (array_key_exists('min-length', $rules) && $length < (int) $rules['min-length']) {
            return ValidationOutcome::fail(
                'min-length',
                sprintf('Subject is too short: %d characters (minimum %d).', $length, (int) $rules['min-length']),
                null,
                $length
            );
        }

        if (array_key_exists('max-length', $rules) && $length > (int) $rules['max-length']) {
            return ValidationOutcome::fail(
                'max-length',
                sprintf('Subject is too long: %d characters (maximum %d).', $length, (int) $rules['max-length']),
                null,
                $length
            );
        }

        if (array_key_exists('pattern', $rules) && preg_match((string) $rules['pattern'], $subject) !== 1) {
            return ValidationOutcome::fail(
                'pattern',
                (string) ($rules['pattern-message'] ?? 'Subject must match pattern: ' . $rules['pattern']),
                isset($rules['pattern-example']) ? (string) $rules['pattern-example'] : null,
                $length
            );
        }

        if ((bool) ($rules['forbid-trailing-period'] ?? false) && substr(rtrim($subject), -1) === '.') {
            return ValidationOutcome::fail(
                'forbid-trailing-period',
                "Subject must not end with a period ('.').",
                null,
                $length
            );
        }

        $caseOutcome = $this->validateSubjectCase($subject, $rules, $length);
        if ($caseOutcome !== null) {
            return $caseOutcome;
        }

        return ValidationOutcome::pass($length);
    }

    /**
     * Subject begins with the literal `Merge ` (case-insensitive, matching how
     * Git generates merge subjects) or with `squash! ` / `fixup! ` (literals
     * generated by `git commit --squash`/`--fixup`). Heuristic by subject only
     * (CON-004) — the commit graph is never inspected.
     */
    private function isMergeLike(string $subject): bool
    {
        return stripos($subject, 'Merge ') === 0
            || strpos($subject, 'squash! ') === 0
            || strpos($subject, 'fixup! ') === 0;
    }

    /**
     * @param array<string, mixed> $rules
     */
    private function validateSubjectCase(string $subject, array $rules, int $length): ?ValidationOutcome
    {
        $case = $rules['subject-case'] ?? null;
        if ($case === null) {
            return null;
        }

        $rest = $this->stripConventionalPrefix($subject);

        if ($case === 'lowercase' && preg_match('/[A-Z]/', $rest) === 1) {
            return ValidationOutcome::fail(
                'subject-case',
                'Subject must be lowercase (no capital letters after the type prefix).',
                null,
                $length
            );
        }

        if ($case === 'sentence' && preg_match('/^[A-Z]/', $rest) !== 1) {
            return ValidationOutcome::fail(
                'subject-case',
                'Subject must start with a capital letter (sentence case).',
                null,
                $length
            );
        }

        return null;
    }

    /**
     * Strip the optional Conventional-Commits prefix so subject-case is
     * evaluated against the description, not the `tipo(scope): ` token. When
     * there is no prefix the whole subject is the description.
     */
    private function stripConventionalPrefix(string $subject): string
    {
        if (preg_match(self::CC_PREFIX, $subject, $matches) === 1) {
            return substr($subject, strlen($matches[0]));
        }
        return $subject;
    }
}
