<?php

declare(strict_types=1);

namespace Wtyd\GitHooks\App\Commands;

use LaravelZero\Framework\Commands\Command;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use Wtyd\GitHooks\Configuration\ConfigurationParser;
use Wtyd\GitHooks\Configuration\ConfigurationResult;
use Wtyd\GitHooks\Configuration\JobConfiguration;
use Wtyd\GitHooks\Exception\GitHooksExceptionInterface;
use Wtyd\GitHooks\Jobs\JobRegistry;

class CacheClearCommand extends Command
{
    protected $signature = 'cache:clear
                            {names?* : Job or flow names to clear (all if omitted)}
                            {--config= : Path to configuration file}';

    protected $description = 'Clear cache files generated by QA tools';

    private ConfigurationParser $parser;

    private JobRegistry $jobRegistry;

    public function __construct(ConfigurationParser $parser, JobRegistry $jobRegistry)
    {
        parent::__construct();
        $this->parser = $parser;
        $this->jobRegistry = $jobRegistry;
    }

    public function handle(): int
    {
        $configFile = strval($this->option('config'));
        /** @var string[] $requestedNames */
        $requestedNames = $this->argument('names');

        try {
            $config = $this->parser->parse($configFile);

            if ($config->isLegacy()) {
                $this->error("cache:clear requires v3 configuration format (hooks/flows/jobs).");
                return 1;
            }

            if ($config->hasErrors()) {
                foreach ($config->getValidation()->getErrors() as $error) {
                    $this->error($error);
                }
                return 1;
            }

            $hasErrors = false;
            $jobs = $this->resolveJobs($config, $requestedNames, $hasErrors);

            if (empty($jobs)) {
                $this->info('No jobs to clear.');
                return $hasErrors ? 1 : 0;
            }

            $cleared = $this->clearJobCaches($jobs);

            $this->line('');
            $this->info("Cache clear complete: $cleared item(s) deleted.");

            return $hasErrors ? 1 : 0;
        } catch (GitHooksExceptionInterface $e) {
            $this->error($e->getMessage());
            return 1;
        }
    }

    /**
     * @param string[] $requestedNames
     * @return array<string, JobConfiguration>
     */
    private function resolveJobs(ConfigurationResult $config, array $requestedNames, bool &$hasErrors): array
    {
        $allJobs = $config->getJobs();

        if (empty($requestedNames)) {
            return $allJobs;
        }

        $filtered = [];
        foreach ($requestedNames as $name) {
            if (isset($allJobs[$name])) {
                $filtered[$name] = $allJobs[$name];
                continue;
            }

            $flow = $config->getFlow($name);
            if ($flow !== null) {
                foreach ($flow->getJobs() as $jobName) {
                    if (isset($allJobs[$jobName]) && !isset($filtered[$jobName])) {
                        $filtered[$jobName] = $allJobs[$jobName];
                    }
                }
                continue;
            }

            $this->warn("'$name' is not a job or flow in the configuration.");
            $hasErrors = true;
        }
        return $filtered;
    }

    /**
     * @param array<string, JobConfiguration> $jobs
     */
    private function clearJobCaches(array $jobs): int
    {
        $cleared = 0;

        foreach ($jobs as $name => $jobConfig) {
            $jobInstance = $this->jobRegistry->create($jobConfig);
            $cachePaths = $jobInstance->getCachePaths();

            foreach ($cachePaths as $path) {
                $cleared += $this->clearPath($name, $path);
            }
        }

        return $cleared;
    }

    private function clearPath(string $jobName, string $path): int
    {
        if (is_dir($path)) {
            $this->deleteDirectory($path);
            $this->line("  \e[32m\u{2714}\e[0m $jobName: deleted directory $path");
            return 1;
        }

        if (file_exists($path)) {
            unlink($path);
            $this->line("  \e[32m\u{2714}\e[0m $jobName: deleted $path");
            return 1;
        }

        $this->line("  \e[90m- $jobName: $path (not found)\e[0m");
        return 0;
    }

    private function deleteDirectory(string $dir): void
    {
        $items = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($items as $item) {
            if ($item->isDir()) {
                rmdir($item->getRealPath());
            } else {
                unlink($item->getRealPath());
            }
        }

        rmdir($dir);
    }
}
