<?php

namespace Wtyd\GitHooks\App\Commands;

use Exception;
use LaravelZero\Framework\Commands\Command;
use Wtyd\GitHooks\Configuration\ConfigurationParser;
use Wtyd\GitHooks\Hooks;
use Wtyd\GitHooks\Hooks\HookInstaller;
use Wtyd\GitHooks\Utils\Printer;
use Wtyd\GitHooks\Utils\Storage;

class CreateHookCommand extends Command
{
    protected $signature = 'hook
                            {hook=pre-commit : The hook to install (default: pre-commit). When using v3 config, installs all hooks defined in the config.}
                            {scriptFile? : Custom script file for legacy mode}
                            {--legacy : Force legacy installation (.git/hooks/ instead of core.hooksPath)}
                            {--config= : Path to configuration file}';

    protected $description = 'Install git hooks. With v3 config, uses core.hooksPath and installs all configured hooks.';

    protected Printer $printer;

    private ConfigurationParser $parser;

    private HookInstaller $installer;

    public function __construct(Printer $printer, ConfigurationParser $parser, HookInstaller $installer)
    {
        $this->printer = $printer;
        $this->parser = $parser;
        $this->installer = $installer;
        parent::__construct();
    }

    public function handle()
    {
        $hook = strval($this->argument('hook'));

        // If a custom script file is provided, always use legacy mode
        if (!empty($this->argument('scriptFile'))) {
            return $this->handleLegacy();
        }

        // If the hook argument is not a valid git hook, report error
        // (catches cases like: hook MyScript.php where scriptFile is missing)
        if (!Hooks::validate($hook)) {
            $this->printer->error("'$hook' is not a valid git hook. Available hooks are:");
            $this->printer->error(implode(', ', Hooks::HOOKS));
            return 1;
        }

        if ($this->option('legacy')) {
            return $this->handleLegacy();
        }

        return $this->handleV3();
    }

    private function handleV3(): int
    {
        $configFile = strval($this->option('config'));

        try {
            $config = $this->parser->parse($configFile);
        } catch (\Throwable $e) {
            // No config found — fall back to legacy single-hook install
            return $this->handleLegacy();
        }

        if ($config->isLegacy()) {
            return $this->handleLegacy();
        }

        $hooks = $config->getHooks();

        if ($hooks === null || empty($hooks->getEvents())) {
            $this->printer->warning("No hooks defined in configuration. Nothing to install.");
            return 0;
        }

        $events = $hooks->getEvents();
        $command = $hooks->getCommand();
        $created = $this->installer->install($events, $command);

        foreach ($created as $path) {
            $event = basename($path);
            $this->printer->success("Hook $event installed");
        }

        $this->info("  hooks path: .githooks (configured via core.hooksPath)");

        return 0;
    }

    private function handleLegacy(): int
    {
        $hook = strval($this->argument('hook'));
        $scriptFile = strval($this->argument('scriptFile'));

        if (!Hooks::validate($hook)) {
            $this->printer->error("'$hook' is not a valid git hook. Available hooks are:");
            $this->printer->error(implode(', ', Hooks::HOOKS));
            return 1;
        }

        if (!empty($scriptFile)) {
            return $this->installCustomScript($hook, $scriptFile);
        }

        try {
            $destiny = ".git/hooks/$hook";

            if (Storage::exists($destiny)) {
                Storage::delete($destiny);
            }

            $scriptContent = "#!/bin/sh\n# Generated by GitHooks — do not edit manually\n"
                . "php vendor/bin/githooks hook:run \"$(basename \"$0\")\"\n";

            Storage::put($destiny, $scriptContent);
            Storage::chmod($destiny, 0755);

            $this->printer->success("Hook $hook created");
            return 0;
        } catch (\Throwable $th) {
            $this->printer->error("Error installing hook $hook");
            return 1;
        }
    }

    private function installCustomScript(string $hook, string $scriptFile): int
    {
        if (!Storage::exists($scriptFile)) {
            $this->printer->error("$scriptFile file not found");
            return 1;
        }

        try {
            $destiny = ".git/hooks/$hook";

            if (Storage::exists($destiny)) {
                Storage::delete($destiny);
            }

            Storage::copy($scriptFile, $destiny);
            Storage::chmod($destiny, 0755);

            $this->printer->success("Hook $hook created with custom script $scriptFile");
            return 0;
        } catch (\Throwable $th) {
            $this->printer->error("Error copying $scriptFile to $hook");
            return 1;
        }
    }
}
