<?php

declare(strict_types=1);

namespace Wtyd\GitHooks\Hooks;

use Wtyd\GitHooks\Hooks as HooksConstants;

class HookInstaller
{
    private const DEFAULT_COMMAND = 'php vendor/bin/githooks';

    private string $rootPath;

    public function __construct(string $rootPath)
    {
        $this->rootPath = $rootPath;
    }

    /**
     * Install hooks for the given events using core.hooksPath.
     *
     * @param string[] $events
     * @param string $command The GitHooks command prefix (e.g. 'php7.4 vendor/bin/githooks')
     * @return string[] List of created hook file paths
     */
    public function install(array $events, string $command = ''): array
    {
        $hooksDir = $this->rootPath . DIRECTORY_SEPARATOR . '.githooks';

        if (!is_dir($hooksDir)) {
            mkdir($hooksDir, 0755, true);
        }

        $script = $this->buildScript($command);

        $created = [];
        foreach ($events as $event) {
            if (!HooksConstants::validate($event)) {
                continue;
            }
            $filePath = $hooksDir . DIRECTORY_SEPARATOR . $event;
            file_put_contents($filePath, $script);
            chmod($filePath, 0755);
            $created[] = $filePath;
        }

        $this->configureHooksPath();

        return $created;
    }

    /**
     * Install a single event hook.
     */
    public function installSingle(string $event): ?string
    {
        $result = $this->install([$event]);
        return $result[0] ?? null;
    }

    /**
     * Legacy mode: copy hook script to .git/hooks/ (for Git < 2.9).
     *
     * @param string[] $events
     * @param string $command The GitHooks command prefix
     * @return string[]
     */
    public function installLegacy(array $events, string $command = ''): array
    {
        $gitHooksDir = $this->rootPath . DIRECTORY_SEPARATOR . '.git' . DIRECTORY_SEPARATOR . 'hooks';

        if (!is_dir($gitHooksDir)) {
            return [];
        }

        $script = $this->buildScript($command);

        $created = [];
        foreach ($events as $event) {
            if (!HooksConstants::validate($event)) {
                continue;
            }
            $filePath = $gitHooksDir . DIRECTORY_SEPARATOR . $event;
            file_put_contents($filePath, $script);
            chmod($filePath, 0755);
            $created[] = $filePath;
        }

        return $created;
    }

    /**
     * Clean installed hooks: remove .githooks/ dir and unset core.hooksPath.
     */
    public function clean(): void
    {
        $hooksDir = $this->rootPath . DIRECTORY_SEPARATOR . '.githooks';

        if (is_dir($hooksDir)) {
            $files = glob($hooksDir . DIRECTORY_SEPARATOR . '*') ?: [];
            array_map('unlink', $files);
            rmdir($hooksDir);
        }

        $this->unsetHooksPath();
    }

    /**
     * Clean legacy hooks from .git/hooks/.
     *
     * @param string[] $events Events to remove. Empty = remove all known events.
     */
    public function cleanLegacy(array $events = []): void
    {
        $gitHooksDir = $this->rootPath . DIRECTORY_SEPARATOR . '.git' . DIRECTORY_SEPARATOR . 'hooks';

        if (empty($events)) {
            $events = HooksConstants::HOOKS;
        }

        foreach ($events as $event) {
            $filePath = $gitHooksDir . DIRECTORY_SEPARATOR . $event;
            if (file_exists($filePath)) {
                unlink($filePath);
            }
        }
    }

    private function buildScript(string $command): string
    {
        $cmd = !empty($command) ? $command : self::DEFAULT_COMMAND;

        return "#!/bin/sh\n# Generated by GitHooks — do not edit manually\n"
            . "$cmd hook:run \"\$(basename \"\$0\")\"\n";
    }

    protected function configureHooksPath(): void
    {
        $this->exec('git config core.hooksPath .githooks');
    }

    protected function unsetHooksPath(): void
    {
        $this->exec('git config --unset core.hooksPath');
    }

    private function exec(string $command): void
    {
        $cwd = getcwd();
        chdir($this->rootPath);
        shell_exec($command . ' ' . \Wtyd\GitHooks\Utils\Platform::stderrRedirect());
        if ($cwd !== false) {
            chdir($cwd);
        }
    }
}
