name: Code Analysis
# https://github.com/shivammathur/setup-php
on:
  push:
   branches-ignore: [ rc**, main-tests ]
  pull_request:
    branches-ignore: [ master ]

env:
  extensions: mbstring #intl, pcov

jobs:
  githooks:
    name: GitHooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          tools/tmp/resultCache.php #Phpstan cache
          /home/runner/.cache/composer/files
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        chmod -R +x tools/*
        tools/composer install --prefer-dist --no-progress

    - name: Execute GitHooks
      run: php githooks tool all full

  Code_Analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          tools/tmp/resultCache.php #Phpstan cache
          /home/runner/.cache/composer/files
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        chmod -R +x tools/*
        tools/composer install --prefer-dist --no-progress

    - name: Execute PhpStan
      id: phpstan
      run: php githooks tool phpstan
      continue-on-error: true

    - name: Execute Php Mess Detector
      id: phpmd
      run: php githooks tool phpmd
      continue-on-error: true

    - name: Execute Php Code Sniffer
      id: phpcs
      run: php githooks tool phpcs
      continue-on-error: true

    - name: Check on failures
      if: steps.phpstan.outcome != 'success' || steps.phpmd.outcome != 'success' || steps.phpcs.outcome != 'success'
      run: exit 1
