name: Executable Finder
# https://github.com/shivammathur/setup-php
on:
  push:
    branches-ignore: [ master ] #on master it only runs on ubuntu to speed up

  pull_request:
    branches-ignore: [ master ]

env:
  extensions: mbstring #intl, pcov

jobs:
  executable_finder_test_local: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4']
    name: Executable Finder on Local Test (${{ matrix.operating-system }}, PHP ${{ matrix.php-versions }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }}
        tools: phpcpd #I can't put it as dependency
        ini-values: "post_max_size=256M"
        coverage: none
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Testing the Executable Finder
      run: vendor/bin/phpunit tests/System/ExecutableFinderTest.php

  executable_finder_test_phar: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4']
    name: Executable Finder on Phar Test (${{ matrix.operating-system }}, PHP ${{ matrix.php-versions }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: phpunit:9
        ini-values: "post_max_size=256M" #optional
        coverage: none
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Install Mockery
      run: composer global require mockery/mockery

    - name: Composer dumpautoload
      run: composer dumpautoload

    - name: Download tools as .Phars in Unix
      if: ${{ ('ubuntu-latest' == matrix.operating-system || 'macos-latest' == matrix.operating-system) }}
      run: |
        wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        wget https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
        wget https://phpmd.org/static/latest/phpmd.phar &&
        wget https://github.com/phpstan/phpstan/releases/download/0.12.49/phpstan.phar
        wget https://phar.phpunit.de/phpcpd.phar

    - name: Download tools as .Phars in Windows
      if: ${{ 'windows-latest' == matrix.operating-system }}
      run: |
        curl -o phpcs.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        curl -o phpcbf.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
        curl -o phpmd.phar https://phpmd.org/static/latest/phpmd.phar &&
        curl -o phpstan.phar https://github.com/phpstan/phpstan/releases/download/0.12.49/phpstan.phar
        curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar

    - name: Testing the Executable Finder
      run: phpunit tests/System/ExecutableFinderTest.php

  executable_finder_test_global: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4']
    name: Executable Finder on Global Test (${{ matrix.operating-system }}, PHP ${{ matrix.php-versions }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: phpcs, phpcbf, phpmd, phpstan, phpcpd, phpunit:9
        ini-values: "post_max_size=256M" #optional
        coverage: none
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Install Mockery
      run: composer global require mockery/mockery

    - name: Composer dumpautoload
      run: composer dumpautoload

    - name: Testing the Executable Finder
      run: phpunit tests/System/ExecutableFinderTest.php
