name: Feature CI
# https://github.com/shivammathur/setup-php
on:
  push:
    branches-ignore: [ master, phar ]

  pull_request:
    branches-ignore: [ master ]

env:
  extensions: mbstring #intl, pcov

jobs:
  tests:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '8.0'] 
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: phpcs, phpcbf, phpmd, phpstan
        ini-values: "post_max_size=256M" #optional
        coverage: none
  
    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install Phpcpd for php 7.1
      if: ${{ ('7.2' == matrix.php-versions || '7.1' == matrix.php-versions) }}
      run:   wget -O phpcpd.phar https://phar.phpunit.de/phpcpd-3.0.1.phar

    - name: Install Phpcpd for php 8.0
      if: ${{ ('8.0' == matrix.php-versions) }}
      run:   wget -O phpcpd.phar https://phar.phpunit.de/phpcpd-6.0.3.phar

    - name: Testing the Aplication
      run: |
        echo -e "\e[42m\e[30m**** Main Test Suite ****\033[0m"
        vendor/bin/phpunit --order-by random
        echo -e "\e[42m\e[30m**** GitfilesTest ****\033[0m"
        vendor/bin/phpunit tests/Integration/GitFilesTest.php