name: Feature CI
# https://github.com/shivammathur/setup-php
on:
  push:
    branches-ignore: [ master ]

  pull_request:
    branches-ignore: [ master ]

env:
  extensions: mbstring #intl, pcov

jobs:
  tests:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04]
        php-versions: ['7.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: phpcs, phpcbf, phpmd, phpstan
        ini-values: "post_max_size=256M" #optional
        coverage: none
  
    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Phpcpd Unix
      if: ${{ ('7.2' == matrix.php-versions || '7.1' == matrix.php-versions) && ('ubuntu-18.04' == matrix.operating-system || 'macos-latest' == matrix.operating-system)}}
      run:   wget -O phpcpd.phar https://phar.phpunit.de/phpcpd-3.0.1.phar

    - name: Testing the Aplication
      run: |
        echo "**** Main Test Suite ****"
        vendor/bin/phpunit --order-by random
        echo "**** GitfilesTest ****"
        vendor/bin/phpunit tests/Integration/GitFilesTest.php