name: Master
# https://github.com/shivammathur/setup-php
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

env:
  extensions: mbstring #intl, pcov
jobs:
  executable_finder_test_local: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4']
    name: Executable Finder on Local Test (${{ matrix.operating-system }}, PHP ${{ matrix.php-versions }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        ini-values: "post_max_size=256M" #optional
        coverage: none
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Testing the Executable Finder
      run: vendor/bin/phpunit tests/System/ExecutableFinderTest.php

  executable_finder_test_phar: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4']
    name: Executable Finder on Phar Test (${{ matrix.operating-system }}, PHP ${{ matrix.php-versions }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: prestissimo, phpunit:8.5.0 #, phpcs, phpcbf, phpmd, phpstan, phpcpd, 
        ini-values: "post_max_size=256M" #optional
        coverage: none
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Composer dumpautoload
      run: composer dumpautoload

    - name: Download tools as .Phars in Unix
      run: wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && wget https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && wget https://phpmd.org/static/latest/phpmd.phar &&
            wget https://github.com/phpstan/phpstan/releases/download/0.12.49/phpstan.phar && wget https://phar.phpunit.de/phpcpd.phar
      if: ${{ ('ubuntu-latest' == matrix.operating-system || 'macos-latest' == matrix.operating-system) }}

    - name: Download tools as .Phars in Windows
      run: curl -o phpcs.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && curl -o phpcbf.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && curl -o phpmd.phar https://phpmd.org/static/latest/phpmd.phar &&
            curl -o phpstan.phar https://github.com/phpstan/phpstan/releases/download/0.12.49/phpstan.phar && curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
      if: ${{ 'windows-latest' == matrix.operating-system }}
      
    - name: Testing the Executable Finder
      run: phpunit tests/System/ExecutableFinderTest.php

  executable_finder_test_global: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4']
    name: Executable Finder on Global Test (${{ matrix.operating-system }}, PHP ${{ matrix.php-versions }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: prestissimo, phpcs, phpcbf, phpmd, phpstan, phpcpd, phpunit:8.5.0
        ini-values: "post_max_size=256M" #optional
        coverage: none
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Composer dumpautoload
      run: composer dumpautoload

    - name: Testing the Executable Finder
      run: phpunit tests/System/ExecutableFinderTest.php

  all-tests:    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] #ubuntu-latest, macos-latest, windows-latest
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Full Tests on ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: prestissimo, phpcs, phpcbf, phpmd, phpstan, phpcpd
        ini-values: "post_max_size=256M" #optional
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Install Phpcpd Unix
      run:   wget -O phpcpd.phar https://phar.phpunit.de/phpcpd-3.0.1.phar
      if: ${{ ('7.2' == matrix.php-versions || '7.1' == matrix.php-versions) && ('ubuntu-latest' == matrix.os || 'macos-latest' == matrix.os)}}

    - name: Install Phpcpd Windows
      run:   curl -o phpcpd.phar https://phar.phpunit.de/phpcpd-3.0.1.phar
      if: ${{ ('7.2' == matrix.php-versions || '7.1' == matrix.php-versions) && 'windows-latest' == matrix.os}}

    - name: Testing the Aplication
      run: vendor/bin/phpunit
