name: Windows Tests
# https://github.com/shivammathur/setup-php
on:
  push:
    branches-ignore: [ rc** ]
  pull_request:
    branches-ignore: [ master ]

env:
  extensions: :opcache, fileinfo #intl, pcov #fileinfo is needed for Windows

jobs:
  tests:    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        php-versions: ['7.1', '8.0']
    name: PHP ${{ matrix.php-versions }} Windows Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }} #optional
        tools: phpcs, phpcbf, phpmd, phpstan, phpcpd
        ini-values: "post_max_size=256M" #optional
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Parallel-Lint
      run: composer global require php-parallel-lint/php-parallel-lint

    - name: Install Phpcpd Windows
      run:   curl -o phpcpd.phar https://phar.phpunit.de/phpcpd-3.0.1.phar
      if: ${{ ('7.2' == matrix.php-versions || '7.1' == matrix.php-versions) && 'windows-latest' == matrix.os}}

    - name: Testing the Aplication
      run: vendor/bin/phpunit --group windows
